<?php
/**
 * @file
 * CIT jieyyal custom module.
 */

/**
 * Implements hook_menu().
 */
function cit_jieyyal_menu() {
  $items = array();
  $items['admin/config/cit-jieyyal'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => "CIT Jieyyal Config",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_cit_jieyyal_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Config settings form.
 */
function _cit_jieyyal_admin_settings($form, $form_state) {
  $form['common_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Common settings'),
  );
  $form['common_settings']['cit_jieyyal_config_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => variable_get('cit_jieyyal_config_name'),
    '#description' => t('Type the config name.'),
  );
  return system_settings_form($form);
}